### ISSUE TITLE
LIVE plugin cannot start, brings VDR to restart loop

### ISSUE THREAD

**Issue by michi1972-dev** [lapicidae/vdr-server#25]
Today the VDR was beginning to loop in an error:

```
┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄⚟ Start VDR ⚞┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
vdr: /usr/lib/vdr/plugins/libvdr-live.so.2.6.7: undefined symbol: _ZN7vdrlive12FFmpegThread11StartFFmpegENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii
user.err: Jul 23 13:28:09 vdr: [42617] ERROR: /usr/lib/vdr/plugins/libvdr-live.so.2.6.7: undefined symbol: _ZN7vdrlive12FFmpegThread11StartFFmpegENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii
VDR exit code: 2
```

I didn't change anything, what can I do?

My docker config:

```
services:
  vdr-server:
    image: lapicidae/vdr-server
    container_name: vdr-server
############################
    network_mode: "host"
############################
    environment:
      - PUID=1005
      - PGID=100
      - TZ=Europe/Berlin
      - PLUGINS=epgsearch live streamdev-server vnsiserver satip markad #optional
    volumes:
      - /zfs-pool/container-data/vdr/system:/vdr/system
      - /zfs-pool/container-data/vdr/config:/vdr/config
      - /zfs-pool/vdr/data/tv:/vdr/recordings
      - /zfs-pool/container-data/vdr/cache:/vdr/cache
      - /zfs-pool/container-data/vdr/channellogos:/vdr/channellogos #optional
      - /zfs-pool/container-data/vdr/log:/vdr/log #optional
      - /zfs-pool/container-data/vdr/timeshift:/vdr/timeshift #optional
      - /zfs-pool/container-data/vdr/pkgbuild:/vdr/pkgbuild #optional
      - /zfs-pool/container-data/vdr/scripts:/vdr/scripts:ro
    ports:
#      - 31900-31907:31900-31907/udp #satip rdp
      - 24010-24029:24010-24029/udp #for satip, reference to 50-satip.conf!
      - 8008:8008
      - 6419:6419 #optional
      - 6419:6419/udp #optional
      - 34890:34890 #optional
      - 8099:8099 #optional
#    devices:
#      - /dev/dvb:/dev/dvb #optional
#    cap_add:
#      - SYS_TIME #optional: read hint!
    restart: unless-stopped
    stop_grace_period: 90s #important
    mem_reservation: "20M"
    mem_limit: "350M"
    labels:
      - "autoheal=true"
    healthcheck:
      test: echo "plug satip list \n quit"|nc -w1 localhost 6419|grep -i 900
      interval: 40s
      timeout: 30s
      retries: 2
      start_period: 60s

  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    mem_reservation: "6M"
    mem_limit: "6M"
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     
```
