### ISSUE TITLE
Configuration Reset after Update?

### ISSUE THREAD

**Issue by fabolhak** [lapicidae/vdr-server#6]
Hello,
thank you for this wonderful image. It was really easy to setup and I use it with a combination of [watchtower](https://containrrr.dev/watchtower/) to automatically update the container.

When checking again today it seems that some configuration values I changed and the password for the webui seem to be reset. After a quick test it seems that the config changes are persistent to container restarts. 

So I was wondering if this reset could be due to an automatic update with a new version? Or is there any other mechanism which sets the configuration to default values?

My docker compose file looks like this:
```
version: "2.1"
volumes:
  config:
  system:
  cache:

services:
  vdr-server:
    image: lapicidae/vdr-server
    container_name: vdr-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PLUGINS=live 
      #streamdev-server vnsiserver epgsearch 
    volumes:
      - system:/vdr/system
      - config:/vdr/config
      - /data/vdr:/vdr/recordings
      - cache:/vdr/cache
      - /etc/letsencrypt/live/my.domain/fullchain.pem:/vdr/fullchain.pem:ro
      - /etc/letsencrypt/live/my.domain/privkey.pem:/vdr/privkey.pem:ro
    ports:
      - 8001:8009
      #- 6419:6419 #optional
      #- 6419:6419/udp #optional
      #- 34890:34890 #optional
    devices:
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
